export var garland = [
  { id: 0, color: "red" },
  { id: 1, color: "blue" },
  { id: 2, color: "red" },
  { id: 3, color: "blue" },
  { id: 4, color: "red" },
  { id: 5, color: "blue" },
  { id: 6, color: "yellow" },
  { id: 7, color: "blue" },
  { id: 8, color: "green" },
  { id: 9, color: "black" },
  { id: 10, color: "red" },
  { id: 11, color: "blue" },
  { id: 12, color: "red" },
  { id: 13, color: "blue" },
  { id: 14, color: "red" },
  { id: 15, color: "blue" },
  { id: 16, color: "yellow" },
  { id: 17, color: "blue" },
  { id: 18, color: "green" },
  { id: 19, color: "black" },
];
